//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturaReserva
    {
        public int Codigo { get; set; }
        public int Numero { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorUnitario { get; set; }
        public int IdServicio { get; set; }
    
        public virtual Servicio Servicio { get; set; }
        public virtual FacturaReserva FacturaReserva { get; set; }
    }
}
