//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturaReserva
    {
        public int Id { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> IdReserva { get; set; }
        public Nullable<int> IdServicio { get; set; }

        [JsonIgnore]
        public virtual Reserva Reserva { get; set; }
        [JsonIgnore]
        public virtual Servicio Servicio { get; set; }
    }
}
