//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturaProducto
    {
        public int Codigo { get; set; }
        public int Numero { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorUnitario { get; set; }
        public int IdProducto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual FacturaProducto FacturaProducto { get; set; }
    }
}
