//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturaProducto
    {
        public int Id { get; set; }
        public Nullable<int> IdFacturaProducto { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }

		[JsonIgnore]
		public virtual FacturaProducto FacturaProducto { get; set; }
		[JsonIgnore]
		public virtual Producto Producto { get; set; }
    }
}
