//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.EspecialidadEmpleadoes = new HashSet<EspecialidadEmpleado>();
        }
    
        public int Id { get; set; }
        public string Documento { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaContratación { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public Nullable<int> IdSede { get; set; }

		[JsonIgnore]
		public virtual Cargo Cargo { get; set; }
		[JsonIgnore]
		public virtual Sede Sede { get; set; }
		[JsonIgnore]
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialidadEmpleado> EspecialidadEmpleadoes { get; set; }
    }
}
