//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadEmpleado
    {
        public Nullable<int> idEspecialidad { get; set; }
        public Nullable<int> documentoEmpleado { get; set; }
        public int idEE { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
