//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadEmpleado
    {
        public int Id { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdEmpleado { get; set; }

		[JsonIgnore]
		public virtual Empleado Empleado { get; set; }
		[JsonIgnore]
		public virtual Especialidad Especialidad { get; set; }
    }
}
