//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaReserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaReserva()
        {
            this.DetalleFacturaReservas = new HashSet<DetalleFacturaReserva>();
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdMetodoPago { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpleado { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaReserva> DetalleFacturaReservas { get; set; }
        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }
        [JsonIgnore]
        public virtual MetodoPago MetodoPago { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
