//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class FacturaReserva
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<int> IdMetodoPago { get; set; }
        public Nullable<int> IdReserva { get; set; }
        public Nullable<decimal> Total { get; set; }

		[JsonIgnore]
		public virtual MetodoPago MetodoPago { get; set; }
		[JsonIgnore]
		public virtual Reserva Reserva { get; set; }
    }
}
