//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int idNomina { get; set; }
        public int documentoEmpleado { get; set; }
        public decimal total { get; set; }

		[JsonIgnore]
		public virtual Empleado Empleado { get; set; }
    }
}
