//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class PromocionServicio
    {
        public int idPromocionServicio { get; set; }
        public int idPromocion { get; set; }
        public int idServicio { get; set; }

		[JsonIgnore]
		public virtual Promocion Promocion { get; set; }

		[JsonIgnore]
		public virtual Servicio Servicio { get; set; }
    }
}
