//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.DetalleReservas = new HashSet<DetalleReserva>();
            this.Facturacions = new HashSet<Facturacion>();
        }
    
        public int idReserva { get; set; }
        public int documentoCliente { get; set; }
        public System.DateTime fechaReserva { get; set; }
        public System.TimeSpan horaReserva { get; set; }
        public int duracion { get; set; }
        public Nullable<int> documentoEmpleado { get; set; }
        public string estado { get; set; }

		[JsonIgnore]
		public virtual Cliente Cliente { get; set; }

		[JsonIgnore]
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReserva> DetalleReservas { get; set; }

		[JsonIgnore]
		public virtual Empleado Empleado { get; set; }

		[JsonIgnore]
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion> Facturacions { get; set; }
    }
}
