//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaRelajarnosREST.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int IdSede { get; set; }
        public int IdFacturaReserva { get; set; }
        public int IdEstado { get; set; }

        [JsonIgnore]
        public virtual Estado Estado { get; set; }
        [JsonIgnore]
        public virtual FacturaReserva FacturaReserva { get; set; }
        [JsonIgnore]
        public virtual Sede Sede { get; set; }
    }
}
